### ISSUE TITLE
Error in PrismsDebugJob(). Requested more than 6 hrs walltime.

### ISSUE THREAD

**Issue by jokerbea** [prisms-center/pbs#4]
Hi I am trying to set a walltime at more than 120 hours. And I have multiple nodes, with 12cores.
i tried changing this function in the template.py script but it doesn't seem to change anything.
Could you help me out please.

**Comment by bpuchala** [comment]
The code in template.py gives examples of how to use construct job.Job, specialized for use of PRISMS Center computational resources at U Michigan and restricts jobs to less than 6 hrs on the debug queue. You can construct a job.Job directly to avoid this limitation.
